[[integrations]]
name = "snooty-cache-plugin"

[build]
publish = "public"
command = ". ./build.sh $REPO_NAME $PARSER_VERSION"

[build.environment]
ORG_NAME = "mongodb"
REPO_NAME = "docs-landing"
BRANCH_NAME = "master"
PARSER_VERSION = "v0.20.6"
