[[integrations]]
name = "snooty-cache-plugin"

[build]
publish = "dist"
command = ". ./build.sh $REPO_NAME $PARSER_VERSION"

[build.environment]
ORG_NAME = "10gen"
REPO_NAME = "docs-mongodb-internal"
BRANCH_NAME = "main"
SITE_NAME = "manual"
PARSER_VERSION = "v0.20.18"
