[[integrations]]
name = "snooty-cache-plugin"

[build]
publish = "public"
command = ". ./build.sh $REPO_NAME $PARSER_VERSION"

[build.environment]
ORG_NAME = "10gen"
REPO_NAME = "docs-tutorials"
BRANCH_NAME = "master"
PARSER_VERSION = "v0.20.2-hotfix"
