# tab item 1
[[toc]]
# prefix = '/drivers/csharp/${version}'
prefix = '/${version}/csharp/bianca.laube/DOP-5382'
label = "C# Quick Start"
url = "/quick-start"

[[toc.items]]
label = 'Overview'
url = '/'

[[toc.items]]
label = 'Get Started'
group = true
[[toc.items.items]]
label = 'Quick Reference'
url = '/quick-reference/'
[[toc.items.items]]
label = "What's new"
url = '/whats-new/'
[[toc.items.items]]
label = 'FAQ'
url = '/faq'

# tab item 2
[[toc]]
label = "Fundamentals"
url = "/fundamentals"

[[toc.items]]
label = "Connection"
group = true
[[toc.items.items]]
label = "Connection Guide"
url = "/fundamentals/connection/connect/"
[[toc.items.items]]
label = "Connection Options"
url = "/fundamentals/connection/connection-options/"
[[toc.items.items]]
label = "Network Compression"
url = "/fundamentals/connection/network-compression/"

[[toc.items]]
label = "CRUD Operations"
group = true
[[toc.items.items]]
label = "Operations with Builders"
url = "/fundamentals/builders/"
[[toc.items.items]]
label = "Write"
url = '/fundamentals/crud/write-operations/'
collapsible = true
[[toc.items.items.items]]
label = "Insert"
url = '/fundamentals/crud/write-operations/insert/'
[[toc.items.items.items]]
label = "Replace"
url = '/fundamentals/crud/write-operations/replace/'
[[toc.items.items.items]]
label = "Update Many"
url = '/fundamentals/crud/write-operations/update-many/'
collapsible = true
[[toc.items.items.items.items]]
label = "Fields"
url = '/fundamentals/crud/write-operations/update-many/fields'
[[toc.items.items.items.items]]
label = "Arrays"
url = '/fundamentals/crud/write-operations/update-many/arrays'
[[toc.items.items]]
label = "Read"
url = '/fundamentals/crud/read-operations/'
collapsible = true
[[toc.items.items.items]]
label = "Retrieve Data"
url = '/fundamentals/crud/read-operations/retrieve/'
[[toc.items.items.items]]
label = "Specify Fields to Return"
url = '/fundamentals/crud/read-operations/project/'


# tab item 3
[[toc]]
label = "Examples"
url = "/usage-examples/"

[[toc.items]]
label = "Updating Documents"
group = true
[[toc.items.items]]
label = "Find a document"
url = "/usage-examples/findOne/"
[[toc.items.items]]
label = "Insert a Document"
url = "/usage-examples/insertOne/"
[[toc.items.items]]
label = "Update a document"
url = "/usage-examples/updateOne/"
[[toc.items.items]]
label = "Issues and Help"
url = "/issues-and-help/"